/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdhudWalletRouteImport } from './routes/adhud.$wallet'
import { Route as CheckoutMockRouteImport } from './routes/checkout.mock'
import { Route as MemberUsernameRouteImport } from './routes/member.$username'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiSubyWebhookRouteImport } from './routes/api/suby/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdhudWalletRoute = AdhudWalletRouteImport.update({
  id: '/adhud/$wallet',
  path: '/adhud/$wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutMockRoute = CheckoutMockRouteImport.update({
  id: '/checkout/mock',
  path: '/checkout/mock',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberUsernameRoute = MemberUsernameRouteImport.update({
  id: '/member/$username',
  path: '/member/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubyWebhookRoute = ApiSubyWebhookRouteImport.update({
  id: '/api/suby/webhook',
  path: '/api/suby/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/network': typeof NetworkRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/adhud/$wallet': typeof AdhudWalletRoute
  '/checkout/mock': typeof CheckoutMockRoute
  '/member/$username': typeof MemberUsernameRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/suby/webhook': typeof ApiSubyWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/network': typeof NetworkRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/adhud/$wallet': typeof AdhudWalletRoute
  '/checkout/mock': typeof CheckoutMockRoute
  '/member/$username': typeof MemberUsernameRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/suby/webhook': typeof ApiSubyWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/network': typeof NetworkRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/adhud/$wallet': typeof AdhudWalletRoute
  '/checkout/mock': typeof CheckoutMockRoute
  '/member/$username': typeof MemberUsernameRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/suby/webhook': typeof ApiSubyWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/network'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/adhud/$wallet'
    | '/checkout/mock'
    | '/member/$username'
    | '/api/stripe/webhook'
    | '/api/suby/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/network'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/adhud/$wallet'
    | '/checkout/mock'
    | '/member/$username'
    | '/api/stripe/webhook'
    | '/api/suby/webhook'
  id:
    | '__root__'
    | '/'
    | '/network'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/adhud/$wallet'
    | '/checkout/mock'
    | '/member/$username'
    | '/api/stripe/webhook'
    | '/api/suby/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NetworkRoute: typeof NetworkRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdhudWalletRoute: typeof AdhudWalletRoute
  CheckoutMockRoute: typeof CheckoutMockRoute
  MemberUsernameRoute: typeof MemberUsernameRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiSubyWebhookRoute: typeof ApiSubyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adhud/$wallet': {
      id: '/adhud/$wallet'
      path: '/adhud/$wallet'
      fullPath: '/adhud/$wallet'
      preLoaderRoute: typeof AdhudWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/mock': {
      id: '/checkout/mock'
      path: '/checkout/mock'
      fullPath: '/checkout/mock'
      preLoaderRoute: typeof CheckoutMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/$username': {
      id: '/member/$username'
      path: '/member/$username'
      fullPath: '/member/$username'
      preLoaderRoute: typeof MemberUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suby/webhook': {
      id: '/api/suby/webhook'
      path: '/api/suby/webhook'
      fullPath: '/api/suby/webhook'
      preLoaderRoute: typeof ApiSubyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NetworkRoute: NetworkRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdhudWalletRoute: AdhudWalletRoute,
  CheckoutMockRoute: CheckoutMockRoute,
  MemberUsernameRoute: MemberUsernameRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiSubyWebhookRoute: ApiSubyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
